---
title: "Sample Size Calculation"
author: "Zhenti"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(pwr)
```

Calculation of effect size

T test $$d=\frac{\mu_1-\mu_2}{\sigma}$$

ANOVA $$f=\sqrt{\frac{\sum_{i-1}^kp_i(mu_i-\mu)^2}{\sigma^2}}$$

Linear model

<https://doi.org/10.3389%2Ffpsyg.2012.00111>$$f^2=\frac{R^2}{1-R^2}$$

Chi\^2 Test $$w=\sqrt{\sum_{i=1}^m\frac{(p0_i-p1_i)^2}{p0_i}}$$

```{r}
pwr.t.test(d=0.5, power = 0.9, type="two.sample",alternative = "two.side")
```

```{r}
pwr.anova.test(k=5,f=0.25,sig.level = 0.05,power = 0.8) #k is the number of groups
```

```{r}
pwr.r.test(r=0.25, sig.level = 0.05,power = 0.9,alternative = c("two.sided"))
```

```{r}
pwr.f2.test(u=3,power = 0.9,sig.level = 0.05,f2=0.07)
```

```{r}
pwr.chisq.test(w=0.1853,df=2,sig.level = 0.05,power = 0.9)
```

Plot the expected sample size in different power and effect size

```{r}
r <- seq(0.1,0.5,0.01)
nr <- length(r)

p <- seq(0.4,0.9,0.1)
np <- length(p)

samsize <- array(numeric(nr*np), dim = c(nr,np))
for (i in 1:np){
  for (j in 1:nr) {
    result <- pwr.r.test(n = NULL, r= r[j],sig.level = 0.05,power = p[i], alternative = "two.sided")
    samsize[j,i] <- ceiling(result$n)
  }
}

xrange <- range(r)
yrange <- round(range(samsize))
colors <- rainbow(length(p))
plot(xrange,yrange,type="n",
     xlab="Correlation coefficient(r)",
     ylab="Sample size (r)")

for (i in 1:np){
  lines(r,samsize[,i],type = 'l',lwd=2,col=colors[i])
}

abline(v=0,h=seq(0,yrange[2],50),lty=2,col='grey89')
abline(h=0,v=seq(xrange[1],xrange[2],0.02),lty=2,col='grey89')

title('Sample size estimation for correlation studies\n sig=0.05 (two-tailed)')
legend('topright',title = 'Power',as.character(p),fill=colors)
```
